Hier werden wir bezüglich Pytorch lernen:
- Methoden zum Rechnen mit Matrizen
- Indexoperationen auf Matrizen
- Data Loading


# 1. Rechnen mit Matrizen

## 1.1 Tensoren erstellen

In [1]:
import torch 

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
A.shape, B.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [2]:
C1 = torch.randn(2, 2)  # Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution)
C2 = torch.zeros(2, 2)  
C1, C2

(tensor([[ 1.3392, -0.5431],
         [-0.4813, -1.6955]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [3]:
C3 = torch.zeros_like(A)  # Returns a tensor filled with zeros with the same shape as input
C3

tensor([[0, 0],
        [0, 0]])

In [4]:
# Einsen
C4 = torch.ones(2, 2)  # Returns a tensor filled with ones
C5 = torch.ones_like(A)  # Returns a tensor filled with ones with the same shape as input matrix A
C4, C5, C4.dtype, C5.dtype

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1, 1],
         [1, 1]]),
 torch.float32,
 torch.int64)

In [5]:
# Einheitsmatrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
# Diagonalmatrix von Vektor
D = torch.tensor([1,2,3,4])
torch.diag(D)

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

In [7]:
torch.diag(D).diag()

tensor([1, 2, 3, 4])

## 1.2 Arbeiten mit Dimensionen

In [8]:
# Transpose 
A.T, torch.t(A), torch.transpose(A, 0, 1) 

(tensor([[1, 3],
         [2, 4]]),
 tensor([[1, 3],
         [2, 4]]),
 tensor([[1, 3],
         [2, 4]]))

In [9]:
A = torch.zeros(2,4,5,7)
A.transpose(1, 2).shape

torch.Size([2, 5, 4, 7])

In [18]:
D.shape

torch.Size([4])

In [10]:
# 0 d vs 1 d
print(D, D.shape)
# Eine Dimension hinzufügen
print(D.unsqueeze(0), D.unsqueeze(0).shape)
print(D.unsqueeze(1), D.unsqueeze(1).shape)

tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])


In [11]:
# Squeeze <-> Unsqueeze rückgängig
D1 = D.unsqueeze(0)
print(D1.squeeze(0), D1.squeeze(0).shape)

tensor([1, 2, 3, 4]) torch.Size([4])


In [12]:
# Broadcasting bei elementweisen Operationen: Addition, Subtraktion, Multiplikation, Division
E = D.unsqueeze(1) 

F = torch.eye(4)
print(E)
print("+")
print(F)
print("=")
print(E+F)

print("In Shapes:")
print(E.shape)
print('+')
print(F.shape)
print('=')
print((E+F).shape)
print("\n-> Die 2. Dimension von E wird 'vervielfacht'")

tensor([[1],
        [2],
        [3],
        [4]])
+
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
=
tensor([[2., 1., 1., 1.],
        [2., 3., 2., 2.],
        [3., 3., 4., 3.],
        [4., 4., 4., 5.]])
In Shapes:
torch.Size([4, 1])
+
torch.Size([4, 4])
=
torch.Size([4, 4])

-> Die 2. Dimension von E wird 'vervielfacht'


In [13]:
# Broadcasting bei elementweisen Operationen: Addition, Subtraktion, Multiplikation, Division
E = D.unsqueeze(0) 

F = torch.eye(4)
print(E)
print("+")
print(F)
print("=")
print(E+F)

tensor([[1, 2, 3, 4]])
+
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
=
tensor([[2., 2., 3., 4.],
        [1., 3., 3., 4.],
        [1., 2., 4., 4.],
        [1., 2., 3., 5.]])


In [14]:
# Besser nicht mit 0-Dimensionalen Tensoren arbeiten! (Hier kann man schnell durcheinander kommen)

In [15]:
# Mehr Broadcasting Beispiele
F + 1, F - 1, F * 2.75, F / 2

(tensor([[2., 1., 1., 1.],
         [1., 2., 1., 1.],
         [1., 1., 2., 1.],
         [1., 1., 1., 2.]]),
 tensor([[ 0., -1., -1., -1.],
         [-1.,  0., -1., -1.],
         [-1., -1.,  0., -1.],
         [-1., -1., -1.,  0.]]),
 tensor([[2.7500, 0.0000, 0.0000, 0.0000],
         [0.0000, 2.7500, 0.0000, 0.0000],
         [0.0000, 0.0000, 2.7500, 0.0000],
         [0.0000, 0.0000, 0.0000, 2.7500]]),
 tensor([[0.5000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.5000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.5000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.5000]]))

## 1.3 Matrix Multiplikation

In [16]:
# Matrix Multiplikation 
torch.matmul(A, B), A @ B, torch.mm(A, B),  # .mm nur für 2D Tensoren
# nutze .matmul (Klarer)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (40x7 and 2x2)

![](2025-03-02-17-46-53.png)

In [151]:
A = torch.randn(12,13,9, 2, 3)  
B = torch.randn(12,13,9, 3, 4)  
C = torch.matmul(A, B)  
C.shape


torch.Size([12, 13, 9, 2, 4])

In [152]:
A = torch.randn(12,13,9, 2, 3)  
B = torch.randn(12,13,10, 3, 4)  
C = torch.matmul(A, B)  

RuntimeError: The size of tensor a (9) must match the size of tensor b (10) at non-singleton dimension 2

In [156]:
torch.matrix_power(torch.eye(3)*2, 3)

tensor([[8., 0., 0.],
        [0., 8., 0.],
        [0., 0., 8.]])

In [ ]:
# Noch viele viele mehr Operationen:
# torch.inverse, torch.det, torch.eig, torch.svd,

## 1.35 Elementwise Matrix Multiplikation


In [17]:
A1 = torch.tensor([[1, 2], [3, 4]])
B1 = torch.tensor([[5, 6], [7, 8]])
A1 * B1, torch.mul(A1, B1)

(tensor([[ 5, 12],
         [21, 32]]),
 tensor([[ 5, 12],
         [21, 32]]))

## 1.4 Aggregatoren

In [83]:
# Einige nützliche Funktionen
T = torch.tensor([1,2,3,4], dtype=torch.float32)
T.sum(), T.mean(), T.std(), T.var(), T.max(), T.min(), T.argmax(), T.argmin()

(tensor(10.),
 tensor(2.5000),
 tensor(1.2910),
 tensor(1.6667),
 tensor(4.),
 tensor(1.),
 tensor(3),
 tensor(0))

In [84]:
M = torch.tensor([[1,2,3], [6,5,4], [7,8,9]], dtype=torch.float32)
print('M:', M)
print('M.sum():', M.sum())
print('M.sum(dim=0):', M.sum(dim=0))
print('M.sum(dim=1):', M.sum(dim=1))

# Analog für mean, std, var, max, min, argmax, argmin

M: tensor([[1., 2., 3.],
        [6., 5., 4.],
        [7., 8., 9.]])
M.sum(): tensor(45.)
M.sum(dim=0): tensor([14., 15., 16.])
M.sum(dim=1): tensor([ 6., 15., 24.])


In [88]:
# Magisches Quadrat 
M = torch.tensor([[4,9,2], [3,5,7], [8,1,6]], dtype=torch.float32)
print('M:', M)
print('M.sum():', M.sum())
print('M.sum(dim=0):', M.sum(dim=0))
print('M.sum(dim=1):', M.sum(dim=1))
print('M.diag().sum():', M.diag().sum())

M: tensor([[4., 9., 2.],
        [3., 5., 7.],
        [8., 1., 6.]])
M.sum(): tensor(45.)
M.sum(dim=0): tensor([15., 15., 15.])
M.sum(dim=1): tensor([15., 15., 15.])
M.diag().sum(): tensor(15.)


In [86]:
# Was ist argmax? Gibt den Index des größten Elements im Tensor zurück
M = torch.tensor([[1,2,3], [6,5,4], [7,9,8]], dtype=torch.float32)
print('M:', M)
print('M.argmax():', M.argmax())
print('M.argmax(dim=0):', M.argmax(dim=0))
print('M.argmax(dim=1):', M.argmax(dim=1))

M: tensor([[1., 2., 3.],
        [6., 5., 4.],
        [7., 9., 8.]])
M.argmax(): tensor(7)
M.argmax(dim=0): tensor([2, 2, 2])
M.argmax(dim=1): tensor([2, 0, 1])


## 1.5 Indexierung

In [104]:
# Indexierung startet bei 0
# M[0,0] -> 1. Zeile, 1. Spalte
# M[1,0] -> 2. Zeile, 1. Spalte
# M[2,2] -> 3. Zeile, 3. Spalte
# : wird verwendet um alle Indices einer Dimension zu selektieren 
# M[1, :] -> 2. Zeile, alle Spalten
# M[:, 1] -> alle Zeilen, 2. Spalte

M = torch.tensor([[1,2,3], [6,5,4], [7,9,8]], dtype=torch.float32)
print( M)
print('M[0,0]:', M[0,0])
print('M[1,0]:', M[1,0])
print('M[2,2]:', M[2,2])
print('M[1, :]:', M[1, :])
print('M[:, 1]:', M[:, 1])


tensor([[1., 2., 3.],
        [6., 5., 4.],
        [7., 9., 8.]])
M[0,0]: tensor(1.)
M[1,0]: tensor(6.)
M[2,2]: tensor(8.)
M[1, :]: tensor([6., 5., 4.])
M[:, 1]: tensor([2., 5., 9.])


In [112]:
# Slicing, nutze  "a:b" um die Elemente von Index a bis b-1 zu selektieren
A = torch.tensor([1,2,3,4,5,6,7,8,9,10])
print(A)
print('A[2:5]:', A[2:5])
print('A[:5]:', A[:5])
print('A[5:]:', A[5:])

# Nutze - um von hinten zu zählen
print('A[-1]:', A[-1])
print('A[-3:]:', A[-3:])
print('A[:-3]:', A[:-3], end='\n\n')

# Analog für mehrdimensionale Tensoren ...
print(M)
print('M[:, 0:2]:', M[:, 0:2])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
A[2:5]: tensor([3, 4, 5])
A[:5]: tensor([1, 2, 3, 4, 5])
A[5:]: tensor([ 6,  7,  8,  9, 10])
A[-1]: tensor(10)
A[-3:]: tensor([ 8,  9, 10])
A[:-3]: tensor([1, 2, 3, 4, 5, 6, 7])

tensor([[1., 2., 3.],
        [6., 5., 4.],
        [7., 9., 8.]])
M[:, 0:2]: tensor([[1., 2.],
        [6., 5.],
        [7., 9.]])


In [118]:
# Zur Vereinfachung wird folgendes Beispiel nur auf 1D Tensoren angewendet, ist aber auf mehrdimensionale Tensoren übertragbar
A = torch.tensor([1,2,3,4,5,6,7,8,9,10]) *10
sortiertes_A, sortierte_Indices = torch.sort(A, descending=True, )

sortiertes_A, sortierte_Indices

(tensor([100,  90,  80,  70,  60,  50,  40,  30,  20,  10]),
 tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [124]:
B = torch.tensor([2,1,3,4,5,6,7,8,9,10]) *11
sortierte_Indices = torch.argsort(A, descending=True)
nach_A_sortierte_B = B[sortierte_Indices]
nach_A_sortierte_B

tensor([110,  99,  88,  77,  66,  55,  44,  33,  11,  22])

In [128]:
# Maskierung, "Masking"
A = torch.tensor([1,2,3,4,5,6,7,8,9,10])
mask = (A > 5) & (A < 8)
mask

tensor([False, False, False, False, False,  True,  True, False, False, False])

In [129]:
A[mask]

tensor([6, 7])

In [131]:
mask = (A == 5) | (A == 8) 
mask, ~mask

(tensor([False, False, False, False,  True, False, False,  True, False, False]),
 tensor([ True,  True,  True,  True, False,  True,  True, False,  True,  True]))

In [133]:
my_mask = torch.zeros(10, dtype=torch.bool)
my_mask[2] = True
my_mask, A[my_mask]

(tensor([False, False,  True, False, False, False, False, False, False, False]),
 tensor([3]))

In [ ]:
# Nutze sort(,...., dim=2) # Sortieren entlang der 2. Dimension


In [36]:
A = torch.tensor([[1,2,3], [6,5,4], [7,9,8]], dtype=torch.float32)
A > 5 

tensor([[False, False, False],
        [ True, False, False],
        [ True,  True,  True]])

In [37]:
A[A > 5]  # -> Es wird immer 1D tensor zurückgegeben

tensor([6., 7., 9., 8.])

In [38]:
A[A > 5] = 0
A

tensor([[1., 2., 3.],
        [0., 5., 4.],
        [0., 0., 0.]])

In [35]:
torch.argwhere(A > 5)

tensor([[1, 0],
        [2, 0],
        [2, 1],
        [2, 2]])

In [39]:
A

tensor([[1., 2., 3.],
        [0., 5., 4.],
        [0., 0., 0.]])

In [40]:
A.unique()

tensor([0., 1., 2., 3., 4., 5.])

In [43]:
A[A > 3] = 0
A.unique(dim=0)

tensor([[0., 0., 0.],
        [1., 2., 3.]])

## 1.6 View, Reshape, Flatten

In [87]:
# neben squeeze, unsqueeze gibt es auch flatten, view, reshape
# M.argmax() 
M.flatten() # -> argmax dann definiert

tensor([1., 2., 3., 6., 5., 4., 7., 9., 8.])

In [ ]:
# .view()

![](2025-03-02-18-01-43.png)
https://stackoverflow.com/questions/42479902/what-does-view-do-in-pytorch

In [ ]:
# Funktioniert nur, wenn die dimensionen aufgehen:
# nxm -> n*m Elemente
# Wollen wir z.B. 3x4 -> 2x6, 6x2, 4x3, 12x1, 1x12

In [94]:
# Nutze -1, wenn du nicht weißt, wie viele Elemente in der Dimension sein sollen
# Wollen in erster Dimension 2 Elemente haben
T = torch.randn(246*3)
T.view(9,-1).shape


torch.Size([9, 82])

In [ ]:
# Was macht .reshape? Genau das gleiche wie view, aber es kopiert die Daten immer (view schlägt fehl, wenn nicht contiguous), kommt gleich
# Call by reference vs Call by value


## Contigous (Zusammenhängend)

Matrix: <br>
![](2025-03-05-20-16-58.png) <br>
Contigous bedeutet, dass in der Matrix benachbarte Elemente im Speicher benachbart vorliegen:
![](2025-03-05-20-17-13.png)

<br><br>
https://stackoverflow.com/a/26999092/9549296

In [48]:
A = torch.tensor([[1, 2], [3, 4]])
B = A.T

A.is_contiguous(), B.is_contiguous()

(True, False)

In [ ]:
B.view(1,4)

# --> .view() schlägt fehl, da B nicht contiguous ist
# --> .reshape() kopiert die Daten in neuen Speicherbereich falls nötig (Checkt Contigous), und funktionert somit auf Tensoren, welche nicht contiguous sind

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [50]:
B = B.contiguous()
B.view(1,4)

tensor([[1, 3, 2, 4]])

### Bsp an Operationen, die non-contigouity erzeugen
- torch.cat 
- torch.stack
- torch.reshape 
- torch.permute
- torch.transpose

Pytorch nimmt contigouity an, weil es dadurch performanter ist. Es muss .contigous() aufgerufen werden, zum checken: .is_contigous()

## Call by reference/ call by value
Wird später wichtig, wenn numerische Gradienten berechnet werden

In [58]:
A = torch.tensor([[1, 2], [3, 4]])
B = A.T
A[0][0] = 10
B

tensor([[10,  3],
        [ 2,  4]])

In [57]:
A = torch.tensor([[1, 2], [3, 4]])
B = A.T.clone()
A[0][0] = 10
B


tensor([[1, 3],
        [2, 4]])

In [59]:
A = torch.tensor([[1, 2], [3, 4]])
B = A.view(1,4)
C = A.reshape(1,4)
A[0][0] = 10
B, C

(tensor([[10,  2,  3,  4]]), tensor([[10,  2,  3,  4]]))

In [63]:
A = torch.tensor([[1, 2], [3, 4]])
C = A.T.reshape(1,4)  # .T macht nicht-contiguous
A[0][0] = 10
C

tensor([[1, 3, 2, 4]])

## Concatenation
Zwei Matrizen in spezifizierter Dimension verbinden. <br>
Nutze: <br>
torch.cat([A,B,C,D,...],dim=x)

(Erzeugt immer neue Kopie der Input-Tensoren)


In [22]:
# Matrizen "konkatenieren" torch.cat / torch.concatenate
A = torch.tensor([[1,2,3], [4,5,6]])
A = A.T
B = torch.tensor([[7,8,9], [10,11,12]]).T
C = torch.cat((A, B, B ), dim=0)
D = torch.cat((A, B), dim=1)
C, D


(tensor([[ 1,  4],
         [ 2,  5],
         [ 3,  6],
         [ 7, 10],
         [ 8, 11],
         [ 9, 12],
         [ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]))

In [23]:
A.shape, B.shape, C.shape, D.shape

(torch.Size([3, 2]),
 torch.Size([3, 2]),
 torch.Size([9, 2]),
 torch.Size([3, 4]))

In [20]:
A[0][0] = 10
C, D

(tensor([[ 1,  4],
         [ 2,  5],
         [ 3,  6],
         [ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]))

In [25]:
A.shape

torch.Size([3, 2])

In [28]:
# Nützlich in Machine Learning um "Trainingsdaten" zu erstellen / Batching
torch.stack((A, A, A)).shape

torch.Size([3, 3, 2])